// Category taxonomy, web-only. Hand-curated per category as the dropdown's column-narrow UX
// rather than derived from presets bundles; the curated shape stays even if a category's
// protocols collectively register every dimType in the catalog.

import type { ColumnKey } from './snapshot'

export const CATEGORIES_EXPECTED: Record<string, readonly ColumnKey[]> = {
  '(none)': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
    'openInterestAtEnd',
    'longOpenInterestAtEnd',
    'shortOpenInterestAtEnd',
  ],
  'AI Agents': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Algo-Stables': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'Anchor BTC': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Basis Trading': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  Bridge: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
    'dailyBridgeVolume',
  ],
  CDP: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  CEX: [],
  'Canonical Bridge': [],
  CeDeFi: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Chain: [],
  'Charity Fundraising': [],
  'Cross Chain Bridge': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
    'dailyBridgeVolume',
  ],
  'DCA Tools': [],
  'DEX Aggregator': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
    'dailyBridgeVolume',
  ],
  'Decentralized AI': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Decentralized BTC': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Derivatives: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
    'dailyPremiumVolume',
    'dailyNormalizedVolume',
    'dailyActiveLiquidity',
    'openInterestAtEnd',
    'longOpenInterestAtEnd',
    'shortOpenInterestAtEnd',
    'dailyActiveUsers',
    'dailyTransactionsCount',
    'dailyGasUsed',
  ],
  'Developer Tools': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Dual-Token Stablecoin': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Farm: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'Gamified Mining': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Gaming: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Governance Incentives': [],
  Indexes: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Insurance: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Launchpad: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  Lending: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'Leveraged Farming': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'Liquid Restaking': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Liquid Staking': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Liquidity Automation': [],
  'Liquidity Manager': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Luck Games': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'NFT Lending': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'NFT Marketplace': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'Onchain Capital Allocator': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Options: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyNotionalVolume',
    'dailyPremiumVolume',
  ],
  'Options Vault': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyNotionalVolume',
    'dailyPremiumVolume',
  ],
  Oracle: [],
  Payments: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  Ponzi: [],
  'Prediction Market': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
    'openInterestAtEnd',
    'longOpenInterestAtEnd',
    'shortOpenInterestAtEnd',
  ],
  Privacy: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
  ],
  'RWA Lending': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Reserve Currency': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Restaked BTC': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Restaking: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Risk Curators': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Services: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  SoFi: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'Staking Pool': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Synthetics: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
    'dailyPremiumVolume',
    'openInterestAtEnd',
    'longOpenInterestAtEnd',
    'shortOpenInterestAtEnd',
  ],
  'Telegram Bot': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'Token Locker': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  'Uncollateralized Lending': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
  ],
  Yield: [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
  'Yield Aggregator': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
  ],
  'Yield Lottery': [
    'dailyFees',
    'dailyRevenue',
    'dailyUserFees',
    'dailyHoldersRevenue',
    'dailyProtocolRevenue',
    'dailySupplySideRevenue',
    'dailyCreatorRevenue',
    'dailyBribesRevenue',
    'dailyTokenTaxes',
    'dailyVolume',
    'dailyNotionalVolume',
  ],
}
