services:
  app:
    build: .
    image: go-http-server:dev
    environment:
      PORT: "3000"
      ENV: "dev"
      LOG_LEVEL: "debug"
      SHUTDOWN_TIMEOUT: "10s"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/http_server?sslmode=disable"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: http_server
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
